name: CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: setup swag
      run: go get github.com/swaggo/swag/cmd/swag

    - name: Build
      run: swag init -g ./cmd/main.go

    - name: Build
      run: go build -v ./cmd/main.go

    - name: Test
      run: go test -v ./...
